import type { ResourceKind } from "./resources";

export type NamingPatternByKind = Record<ResourceKind, string>;

export type NamingPlaceholders = {
  area: string;
  ambiente: string;
};

export const DEFAULT_NAMING_PATTERNS: NamingPatternByKind = {
  vpc: "vpc-AREA-AMBIENTE",
  subnet: "sub-AREA-AMBIENTE",
  vm: "vm-##-AREA-AMBIENTE",
  instancegroup: "ig-AREA-AMBIENTE",
  storage: "gcs-AREA-AMBIENTE",
  sql: "sql-AREA-AMBIENTE",
  gke: "gke-AREA-AMBIENTE",
  nat: "nat-AREA-AMBIENTE",
  router: "router-AREA-AMBIENTE",
  peering: "peer-AREA-AMBIENTE",
  vpn: "vpn-AREA-AMBIENTE",
  interconnect: "ic-AREA-AMBIENTE",
  firewall: "fw-AREA-AMBIENTE",
  dns: "dns-AREA-AMBIENTE",
  artifact: "gar-AREA-AMBIENTE",
  build: "cb-AREA-AMBIENTE",
  kms: "kms-AREA-AMBIENTE",
  internet: "Internet",
  run: "run-AREA-AMBIENTE",
  pubsub: "topic-AREA-AMBIENTE",
  eventarc: "ea-AREA-AMBIENTE",
  bigquery: "bq-AREA-AMBIENTE",
  spanner: "spanner-AREA-AMBIENTE",
  firestore: "fs-AREA-AMBIENTE",
  bigtable: "bt-AREA-AMBIENTE",
  firebase: "firebase-AREA-AMBIENTE",
  workbench: "wb-AREA-AMBIENTE",
  notebook: "nb-AREA-AMBIENTE",
  spark: "spark-AREA-AMBIENTE",
  airflow: "composer-AREA-AMBIENTE",
  dataflow: "dataflow-AREA-AMBIENTE",
  modelregistry: "mr-AREA-AMBIENTE",
  tuning: "tuning-AREA-AMBIENTE",
  evaluation: "eval-AREA-AMBIENTE",
  endpoints: "endpoint-AREA-AMBIENTE",
  batchinference: "batch-inf-AREA-AMBIENTE",
  featurestore: "featurestore-AREA-AMBIENTE",
  experiments: "exp-AREA-AMBIENTE",
  training: "training-AREA-AMBIENTE",
  pipelines: "pipeline-AREA-AMBIENTE",
  mlmonitoring: "ml-mon-AREA-AMBIENTE",
  zone: "zona-AREA-AMBIENTE",
  folder: "folder-AREA-AMBIENTE",
  project: "proj-AREA-AMBIENTE",
  entra: "entra-AREA-AMBIENTE",
  infocard: "info-AREA-AMBIENTE",
  pcuser: "user-AREA-AMBIENTE",
  onprem: "onprem-AREA-AMBIENTE",
  github: "github-AREA-AMBIENTE",
  iam: "iam-AREA-AMBIENTE",
  loadbalancer: "lb-AREA-AMBIENTE",
  cdn: "cdn-AREA-AMBIENTE",
  orgpolicy: "orgpol-AREA-AMBIENTE",
  psc: "psc-AREA-AMBIENTE",
  secretmanager: "secret-AREA-AMBIENTE",
  certificatemanager: "cert-AREA-AMBIENTE",
  apigee: "apigee-AREA-AMBIENTE",
  memorystore: "ms-AREA-AMBIENTE",
  alloydb: "alloydb-AREA-AMBIENTE",
  cloudshell: "shell-AREA-AMBIENTE",
  monitoring: "monitoring-AREA-AMBIENTE",
  cloudlogging: "log-AREA-AMBIENTE",
  cloudarmor: "armor-AREA-AMBIENTE",
  knowledgecatalog: "catalog-AREA-AMBIENTE",
  usergroup: "group-AREA-AMBIENTE",
};

export const NAMING_TOKEN_HINTS = [
  { token: "AREA", description: "Área de negócio (ex.: financeiro)" },
  { token: "AMBIENTE", description: "Ambiente (ex.: prd, hml, dev)" },
  {
    token: "##",
    description: "Sequência numérica com zeros à esquerda (## → 01, ### → 001)",
  },
] as const;
