import {
  ArtifactNode,
  BuildNode,
  KmsNode,
  BigqueryNode,
  SpannerNode,
  FirestoreNode,
  WorkbenchNode,
  GkeNode,
  InternetNode,
  NatNode,
  PeeringNode,
  VpnNode,
  InterconnectNode,
  FirewallNode,
  PubsubNode,
  EventarcNode,
  RunNode,
  SqlNode,
  StorageNode,
  SubnetNode,
  VmNode,
  VpcNode,
  ZoneNode,
  FolderNode,
  InfocardNode,
  EntraNode,
  PcUserNode,
  OnpremNode,
} from "../nodes";

export const nodeTypes = {
  vpc: VpcNode,
  subnet: SubnetNode,
  vm: VmNode,
  storage: StorageNode,
  sql: SqlNode,
  gke: GkeNode,
  nat: NatNode,
  peering: PeeringNode,
  vpn: VpnNode,
  interconnect: InterconnectNode,
  firewall: FirewallNode,
  artifact: ArtifactNode,
  build: BuildNode,
  kms: KmsNode,
  internet: InternetNode,
  run: RunNode,
  pubsub: PubsubNode,
  eventarc: EventarcNode,
  bigquery: BigqueryNode,
  spanner: SpannerNode,
  firestore: FirestoreNode,
  workbench: WorkbenchNode,
  zone: ZoneNode,
  folder: FolderNode,
  infocard: InfocardNode,
  entra: EntraNode,
  pcuser: PcUserNode,
  onprem: OnpremNode,
};
