import {
  ArtifactNode,
  BigqueryNode,
  GkeNode,
  InternetNode,
  NatNode,
  PubsubNode,
  RunNode,
  SqlNode,
  StorageNode,
  SubnetNode,
  VmNode,
  VpcNode,
  ZoneNode,
} from "../nodes";

export const nodeTypes = {
  vpc: VpcNode,
  subnet: SubnetNode,
  vm: VmNode,
  storage: StorageNode,
  sql: SqlNode,
  gke: GkeNode,
  nat: NatNode,
  artifact: ArtifactNode,
  internet: InternetNode,
  run: RunNode,
  pubsub: PubsubNode,
  bigquery: BigqueryNode,
  zone: ZoneNode,
};
